#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Verify grouped orbit recovery using annotated feature IDs and companion scores.

For every model under ``store/results_latest/analysis/feature_ids`` this script:
  1. selects the feature-ID file matching the checkpoint epoch;
  2. reads the exact companion ``epoch*_score.txt`` generated by
     ``generate_grouped_orbit_scores.py``;
  3. rejects invalid rings using score thresholds;
  4. runs or reuses successor-map recovery; and
  5. writes a final Yes / No / N/A summary table.

Ring Recovery Matching Criterion:
--------------------------------
A target ring is considered recovered ("Yes") if a candidate recovered ring satisfies:
  1. Candidate ring size is exactly 12 (`len(candidate) == 12`).
  2. Candidate ring shares at least 10 features with the target ring (`len(set(target) & set(candidate)) >= 10`).

Score validity:
---------------
Before orbit matching, each annotated ring must pass its companion score:
  * Major Chord: score >= 70
  * Minor Chord: score >= 70
  * Forth:       score >= 70

An absent ring, missing score, or sub-threshold score is reported as ``N/A``.
Only a valid ring can receive ``Yes`` or ``No`` from orbit recovery.

Outputs:
  Summary TSV file containing group/model tags and recovery status (Yes / No / N/A).
"""

from __future__ import annotations

import argparse
import csv
import json
import re
import shlex
import subprocess
import sys
from dataclasses import dataclass
from pathlib import Path
from typing import Dict, Iterable, List, Mapping, Optional, Sequence, Tuple


TAG_RE = re.compile(r"\[([^\[\]]+)\]")
INT_RE = re.compile(r"-?\d+")
EPOCH_RE = re.compile(r"epoch[-_]?([0-9]+)", re.IGNORECASE)

RUN_NAME_RE = re.compile(
    r"^[^_]+_([^-]+)_([^-]+)_([^-]+)-([0-9]+)_"
    r"([0-9]+-[0-9]+)_([^_]+)_([0-9]+)_max$"
)

TARGETS: Tuple[Tuple[str, str], ...] = (
    ("major", "major chord"),
    ("minor", "minor chord"),
    ("forth", "forth"),
)

FEATURE_IDS_SUFFIX = "_feature_ids.txt"
SCORES_SUFFIX = "_score.txt"


@dataclass(frozen=True)
class ModelRecord:
    group_dir: Path
    model_dir: Path
    feature_ids_file: Path
    feature: str
    layer: str
    mode: str

    @property
    def group(self) -> str:
        return self.group_dir.name

    @property
    def model(self) -> str:
        return self.model_dir.name

    @property
    def n_saes_hint(self) -> Optional[int]:
        head = self.mode.split("-", 1)[0]
        return int(head) if head.isdigit() else None


def _norm_label(value: str) -> str:
    return " ".join(value.strip().lower().replace("_", " ").split())


def _epoch(path: Path) -> int:
    match = EPOCH_RE.search(path.name)
    return int(match.group(1)) if match else -1


def parse_run_tags(run_name: str) -> Tuple[str, str, str]:
    """Return (feature, layer, mode) from a run-directory name."""
    match = RUN_NAME_RE.match(run_name)
    if match is None:
        raise ValueError(f"Unrecognised model-directory name: {run_name}")
    return match.group(3), match.group(4), match.group(5)


def find_feature_id_files(model_dir: Path) -> List[Path]:
    """Find feature-id files excluding probe_feature_ids files."""
    files = [
        path
        for path in model_dir.glob("epoch*_feature_ids.txt")
        if "probe_feature_ids" not in path.name
    ]
    return sorted(files, key=lambda p: (_epoch(p), p.name))


def discover_models(feature_ids_root: Path) -> List[ModelRecord]:
    records: List[ModelRecord] = []
    for group_dir in sorted(p for p in feature_ids_root.iterdir() if p.is_dir()):
        for model_dir in sorted(p for p in group_dir.iterdir() if p.is_dir()):
            feature_files = find_feature_id_files(model_dir)
            if not feature_files:
                continue
            feature, layer, mode = parse_run_tags(model_dir.name)
            records.append(
                ModelRecord(
                    group_dir=group_dir,
                    model_dir=model_dir,
                    feature_ids_file=feature_files[-1],
                    feature=feature,
                    layer=layer,
                    mode=mode,
                )
            )
    return records


def parse_feature_groups(path: Path) -> Dict[str, List[int]]:
    """Parse feature groups from annotated file."""
    groups: Dict[str, List[int]] = {}
    with path.open("r", encoding="utf-8") as handle:
        for line in handle:
            raw = line.strip()
            if not raw:
                continue
            tags = TAG_RE.findall(raw)
            if not tags:
                continue
            group_name = _norm_label(tags[0])
            rhs = raw.split(":", 1)[1] if ":" in raw else raw
            nums = [int(x) for x in INT_RE.findall(rhs)]
            if not nums:
                continue
            if len(nums) >= 2 and nums[0] == len(nums) - 1:
                nums = nums[1:]
            groups[group_name] = nums
    return groups


def companion_score_path(feature_ids_file: Path) -> Path:
    """Return the exact ``epoch*_score.txt`` companion path.

    Legacy plural ``epoch*_scores.txt`` files are intentionally ignored. This
    prevents stale files from silently affecting the final verification table.
    """
    name = feature_ids_file.name
    if not name.endswith(FEATURE_IDS_SUFFIX):
        raise ValueError(f"Unexpected feature-ids filename: {feature_ids_file}")
    prefix = name[: -len(FEATURE_IDS_SUFFIX)]
    return feature_ids_file.with_name(prefix + SCORES_SUFFIX)


def parse_scores(path: Path, *, strict: bool = False) -> Dict[str, Optional[float]]:
    """Read ``[major]``, ``[minor]``, and ``[forth]`` companion scores."""
    scores: Dict[str, Optional[float]] = {name: None for name, _ in TARGETS}

    if not path.is_file():
        message = f"Missing score file: {path}"
        if strict:
            raise FileNotFoundError(message)
        print(f"[WARN] {message}")
        return scores

    with path.open("r", encoding="utf-8") as handle:
        for line in handle:
            raw = line.strip()
            if not raw or ":" not in raw:
                continue
            label, value = raw.split(":", 1)
            key = _norm_label(label.strip().strip("[]"))
            if key not in scores:
                continue
            text = value.strip()
            if not text or text.lower() in {"n/a", "na", "none"}:
                scores[key] = None
                continue
            try:
                scores[key] = float(text)
            except ValueError as exc:
                raise ValueError(f"Invalid score in {path}: {raw}") from exc

    missing = [name for name, _ in TARGETS if scores[name] is None]
    if missing and strict:
        raise ValueError(f"{path}: missing scores for {', '.join(missing)}")
    if missing:
        print(f"[WARN] {path}: missing scores for {', '.join(missing)}")
    return scores


def ring_is_valid(
    target: Optional[Sequence[int]],
    score: Optional[float],
    minimum_score: float,
) -> bool:
    """A ring is valid only when it exists and its score reaches the cutoff."""
    return target is not None and score is not None and score >= minimum_score


def parse_recovered_rings(path: Path) -> List[List[int]]:
    """Read Ring entries from orbits_raw.txt."""
    rings: List[List[int]] = []
    with path.open("r", encoding="utf-8") as handle:
        for line in handle:
            raw = line.strip()
            if not raw:
                continue
            tags = TAG_RE.findall(raw)
            if not tags or not _norm_label(tags[0]).startswith("ring"):
                continue
            rhs = raw.split(":", 1)[1] if ":" in raw else raw
            nums = [int(x) for x in INT_RE.findall(rhs)]
            if len(nums) >= 2 and nums[0] == len(nums) - 1:
                nums = nums[1:]
            if nums:
                rings.append(nums)
    return rings


def is_ring_match(
    target: Optional[Sequence[int]],
    candidate: Sequence[int],
    min_overlap: int = 10,
) -> bool:
    """Check if candidate matches target ring with size 12 and sufficient feature overlap.
    
    Condition:
      1. Both target and candidate ring must have length 12.
      2. At least `min_overlap` (default: 10) features must be shared between them.
    """
    if target is None:
        return False
    if len(target) != 12 or len(candidate) != 12:
        return False
    
    shared_features = set(target) & set(candidate)
    return len(shared_features) >= min_overlap


def target_ring(
    groups: Mapping[str, Sequence[int]], group_name: str
) -> Optional[List[int]]:
    ids = groups.get(_norm_label(group_name))
    if ids is None or len(ids) < 12:
        return None
    return list(ids[:12])


def ring_status(
    target: Optional[Sequence[int]],
    score: Optional[float],
    minimum_score: float,
    recovered: Iterable[Sequence[int]],
    min_overlap: int = 10,
) -> str:
    """Return N/A for invalid rings; otherwise return orbit recovery Yes/No."""
    if not ring_is_valid(target, score, minimum_score):
        return "N/A"
    return (
        "Yes"
        if any(is_ring_match(target, ring, min_overlap=min_overlap) for ring in recovered)
        else "No"
    )


def _manifest_cells(line: str) -> List[str]:
    stripped = line.strip()
    if not stripped or stripped.startswith("#"):
        return []
    if "\t" in stripped:
        return [cell.strip().strip("\"'") for cell in stripped.split("\t")]
    try:
        return [cell.strip().strip("\"'") for cell in shlex.split(stripped)]
    except ValueError:
        return stripped.split()


def _extract_ckpt_tokens(cells: Sequence[str]) -> List[str]:
    out: List[str] = []
    for cell in cells:
        for match in re.finditer(r"([^\s=]+\.ckpt)", cell):
            out.append(match.group(1).strip("\"'"))
    return out


def _row_mentions_model(cells: Sequence[str], model_name: str) -> bool:
    return any(
        cell == model_name
        or model_name in Path(cell).parts
        or model_name in cell
        for cell in cells
    )


def resolve_checkpoint(
    record: ModelRecord,
    *,
    project_root: Path,
    ckpt_root: Optional[Path],
) -> Path:
    """Resolve the checkpoint listed in the group's ckpts_used.tsv."""
    manifest = record.group_dir / "ckpts_used.tsv"
    if not manifest.is_file():
        raise FileNotFoundError(f"Missing checkpoint manifest: {manifest}")

    raw_paths: List[str] = []
    with manifest.open("r", encoding="utf-8", errors="replace") as handle:
        for line in handle:
            cells = _manifest_cells(line)
            if cells and _row_mentions_model(cells, record.model):
                raw_paths.extend(_extract_ckpt_tokens(cells))

    if not raw_paths:
        raise KeyError(
            f"No checkpoint row for {record.group}/{record.model} in {manifest}"
        )

    candidates: List[Path] = []
    for raw in raw_paths:
        path = Path(raw).expanduser()
        possible = [path] if path.is_absolute() else [
            project_root / path,
            manifest.parent / path,
        ]
        if ckpt_root is not None and not path.is_absolute():
            possible.append(ckpt_root / path)
        for item in possible:
            if item.is_file():
                candidates.append(item.resolve())

    if not candidates and ckpt_root is not None:
        for name in {Path(raw).name for raw in raw_paths}:
            candidates.extend(p.resolve() for p in ckpt_root.rglob(name) if p.is_file())

    if not candidates:
        raise FileNotFoundError(
            f"Checkpoint for {record.group}/{record.model} could not be resolved. "
            f"Manifest values: {raw_paths}. Use --ckpt-root when paths are stale."
        )

    candidates = sorted(
        set(candidates),
        key=lambda p: (
            record.model in p.parts or record.model in str(p),
            _epoch(p),
            str(p),
        ),
        reverse=True,
    )
    return candidates[0]


def choose_feature_ids_file(record: ModelRecord, ckpt_path: Path) -> Path:
    files = find_feature_id_files(record.model_dir)
    ckpt_epoch = _epoch(ckpt_path)
    exact = [path for path in files if _epoch(path) == ckpt_epoch]
    if exact:
        return exact[-1]
    selected = files[-1]
    print(
        f"[WARN] {record.group}/{record.model}: no feature_ids file for "
        f"checkpoint epoch {ckpt_epoch}; using {selected.name}"
    )
    return selected


def recovery_config(
    *,
    ckpt_path: Path,
    module_name: str,
    block: int,
    prob: float,
    device: str,
    sae_idx: Optional[int],
) -> Dict[str, object]:
    return {
        "ckpt_path": str(ckpt_path.resolve()),
        "ckpt_mtime_ns": ckpt_path.stat().st_mtime_ns,
        "module": module_name,
        "block": block,
        "prob": prob,
        "device": device,
        "sae_idx": sae_idx,
    }


def cache_matches(meta_file: Path, expected: Mapping[str, object]) -> bool:
    if not meta_file.is_file():
        return False
    try:
        with meta_file.open("r", encoding="utf-8") as handle:
            existing = json.load(handle)
    except (OSError, json.JSONDecodeError):
        return False
    return existing == dict(expected)


def run_step1_graph(
    *,
    module_name: str,
    ckpt_path: Path,
    out_dir: Path,
    block: int,
    prob: float,
    device: str,
    sae_idx: Optional[int],
) -> None:
    command = [
        sys.executable,
        "-m",
        module_name,
        "--ckpt-path",
        str(ckpt_path),
        "--out-dir",
        str(out_dir),
        "--block",
        str(block),
        "--prob",
        str(prob),
        "--device",
        device,
    ]
    if sae_idx is not None:
        command.extend(["--sae-idx", str(sae_idx)])
    print("[RUN] " + shlex.join(command))
    subprocess.run(command, check=True)


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description=(
            "Verify grouped Major/Minor/Forth orbit recovery using exact "
            "epoch*_score.txt companion files."
        ),
        formatter_class=argparse.ArgumentDefaultsHelpFormatter,
    )
    parser.add_argument(
        "--feature-ids-dir",
        type=Path,
        default=Path("store/results_latest/analysis/feature_ids"),
    )
    parser.add_argument(
        "--out-dir",
        type=Path,
        default=Path("store/results_latest/analysis/orbit_recovery_successor"),
    )
    parser.add_argument(
        "--summary-file",
        type=Path,
        default=None,
        help="Default: <out-dir>/orbit_summary.tsv",
    )
    parser.add_argument("--project-root", type=Path, default=Path.cwd())
    parser.add_argument(
        "--ckpt-root",
        type=Path,
        default=None,
        help="Optional root used to recover stale checkpoint paths.",
    )
    parser.add_argument("--step1-module", default="src.orbits_recovery.obits_recovery")
    parser.add_argument("--block", type=int, default=1024)
    parser.add_argument("--prob", "--threshold", dest="prob", type=float, default=0.5)
    parser.add_argument("--device", default="cuda")
    parser.add_argument(
        "--sae-idx",
        type=int,
        default=None,
        help="Reference SAE. Omit to let step1_graph choose 0 or the middle SAE.",
    )
    parser.add_argument(
        "--min-overlap",
        type=int,
        default=10,
        help="Minimum number of shared features required to declare ring recovery (size must be 12).",
    )
    parser.add_argument(
        "--major-min-score",
        type=float,
        default=70.0,
        help="Minimum RWC chord-root score for the Major Chord ring.",
    )
    parser.add_argument(
        "--minor-min-score",
        type=float,
        default=70.0,
        help="Minimum RWC chord-root score for the Minor Chord ring.",
    )
    parser.add_argument(
        "--forth-min-score",
        type=float,
        default=70.0,
        help="Minimum RWC relative-key accuracy for the Forth ring.",
    )
    parser.add_argument(
        "--strict-scores",
        action="store_true",
        help="Fail when an exact companion epoch*_score.txt file or score is missing.",
    )
    parser.add_argument(
        "--tag-style",
        choices=("group-model", "feature-layer"),
        default="group-model",
        help="Controls the first two summary columns; the file always has five columns.",
    )
    parser.add_argument(
        "--force",
        action="store_true",
        help="Ignore matching recovery metadata and recompute all multi-SAE runs.",
    )
    return parser.parse_args()


def main() -> None:
    print("[SCRIPT] verify_grouped_orbit_recovery.py v1.0")
    args = parse_args()
    feature_ids_root = args.feature_ids_dir.expanduser().resolve()
    out_root = args.out_dir.expanduser().resolve()
    project_root = args.project_root.expanduser().resolve()
    ckpt_root = args.ckpt_root.expanduser().resolve() if args.ckpt_root else None
    summary_file = (
        args.summary_file.expanduser().resolve()
        if args.summary_file is not None
        else out_root / "orbit_summary.tsv"
    )

    if not feature_ids_root.is_dir():
        raise NotADirectoryError(f"Feature-ids root not found: {feature_ids_root}")
    if not project_root.is_dir():
        raise NotADirectoryError(f"Project root not found: {project_root}")
    if ckpt_root is not None and not ckpt_root.is_dir():
        raise NotADirectoryError(f"Checkpoint root not found: {ckpt_root}")
    if args.block <= 0:
        raise ValueError(f"--block must be positive, got {args.block}")

    records = discover_models(feature_ids_root)
    if not records:
        raise RuntimeError(f"No model directories found under {feature_ids_root}")

    out_root.mkdir(parents=True, exist_ok=True)
    summary_file.parent.mkdir(parents=True, exist_ok=True)

    if args.tag_style == "group-model":
        header = ("group", "model", "major", "minor", "forth")
    else:
        header = ("feature", "lid", "major", "minor", "forth")

    rows: List[Tuple[str, str, str, str, str]] = []

    minimum_scores = {
        "major": args.major_min_score,
        "minor": args.minor_min_score,
        "forth": args.forth_min_score,
    }

    for record in records:
        ckpt_path: Optional[Path] = None
        feature_ids_file = record.feature_ids_file

        # Select the feature annotation from the same epoch as the checkpoint
        # before applying score validity or orbit matching.
        if record.n_saes_hint != 1:
            ckpt_path = resolve_checkpoint(
                record,
                project_root=project_root,
                ckpt_root=ckpt_root,
            )
            feature_ids_file = choose_feature_ids_file(record, ckpt_path)

        groups = parse_feature_groups(feature_ids_file)
        targets = {
            column: target_ring(groups, label)
            for column, label in TARGETS
        }
        score_file = companion_score_path(feature_ids_file)
        scores = parse_scores(score_file, strict=args.strict_scores)

        validity = {
            name: ring_is_valid(targets[name], scores[name], minimum_scores[name])
            for name, _ in TARGETS
        }
        for name, _ in TARGETS:
            target_size = len(targets[name]) if targets[name] is not None else 0
            score_text = scores[name] if scores[name] is not None else "N/A"
            reason = (
                "valid"
                if validity[name]
                else (
                    "ring missing/<12 ids"
                    if targets[name] is None
                    else "score missing"
                    if scores[name] is None
                    else f"score<{minimum_scores[name]:g}"
                )
            )
            print(
                f"[CHECK] {record.group}/{record.model} {name}: "
                f"feature_ids={feature_ids_file.name} target_size={target_size} "
                f"score_file={score_file.name} score={score_text} "
                f"cutoff={minimum_scores[name]:g} -> {reason}"
            )

        recovered_rings: List[List[int]] = []
        has_any_valid_target = any(validity.values())

        if has_any_valid_target and record.n_saes_hint != 1:
            assert ckpt_path is not None
            model_out = out_root / record.group / record.model
            orbits_file = model_out / "orbits_raw.txt"
            meta_file = model_out / "recovery_config.json"
            expected_config = recovery_config(
                ckpt_path=ckpt_path,
                module_name=args.step1_module,
                block=args.block,
                prob=args.prob,
                device=args.device,
                sae_idx=args.sae_idx,
            )

            if args.force or not orbits_file.is_file() or not cache_matches(meta_file, expected_config):
                model_out.mkdir(parents=True, exist_ok=True)
                run_step1_graph(
                    module_name=args.step1_module,
                    ckpt_path=ckpt_path,
                    out_dir=model_out,
                    block=args.block,
                    prob=args.prob,
                    device=args.device,
                    sae_idx=args.sae_idx,
                )
                with meta_file.open("w", encoding="utf-8") as handle:
                    json.dump(expected_config, handle, indent=2, sort_keys=True)
                    handle.write("\n")
            else:
                print(f"[CACHED] {orbits_file}")

            if not orbits_file.is_file():
                raise RuntimeError(f"Expected output was not created: {orbits_file}")
            recovered_rings = parse_recovered_rings(orbits_file)

        elif has_any_valid_target:
            print(
                f"[SINGLE-SAE] {record.group}/{record.model}: "
                "valid targets cannot be checked by a cross-SAE successor map"
            )
        else:
            print(
                f"[N/A] {record.group}/{record.model}: "
                "all annotated rings are absent, missing a score, or below threshold"
            )

        major = ring_status(
            targets["major"], scores["major"], minimum_scores["major"],
            recovered_rings, min_overlap=args.min_overlap,
        )
        minor = ring_status(
            targets["minor"], scores["minor"], minimum_scores["minor"],
            recovered_rings, min_overlap=args.min_overlap,
        )
        forth = ring_status(
            targets["forth"], scores["forth"], minimum_scores["forth"],
            recovered_rings, min_overlap=args.min_overlap,
        )

        if args.tag_style == "group-model":
            tag1, tag2 = record.group, record.model
        else:
            tag1, tag2 = record.feature, record.layer
        rows.append((tag1, tag2, major, minor, forth))

        score_text = " ".join(
            f"{name}={scores[name] if scores[name] is not None else 'N/A'}"
            f"/{minimum_scores[name]:g}"
            for name, _ in TARGETS
        )
        print(
            f"[RESULT] {record.group}/{record.model} | "
            f"major={major} minor={minor} forth={forth} | {score_text}"
        )

    with summary_file.open("w", encoding="utf-8", newline="") as handle:
        writer = csv.writer(handle, delimiter="\t", lineterminator="\n")
        writer.writerow(header)
        writer.writerows(rows)

    print(f"[DONE] {summary_file} ({len(rows)} models)")


if __name__ == "__main__":
    main()